server:
  port: 8089

spring:
  application:
    name: elasticsearch-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.178.200:3306/hls?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: hls12345
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 175.24.178.200
    port: 6379
    database: 0
    password: hls12345
    redis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl